let bigD = {
    "Country":"Switzerland",
    "CarType":"Car",
    "CarFuel":"Petrol",
    "CarSize":"Large",
    "CarKm":"25000",
    "Flight Loc":"5000",
    "Flight Int":"40000",
    "Bus":"0",
    "Train":"5000",
    "Cycle":"1000",
    "Walk":"100",
    "Beef (beef herd)":"1000",
    "Dark Chocolate":"100",
    "Lamb & Mutton":"50",
    "Beef (dairy herd)":"0",
    "Coffee":"15",
    "Prawns (farmed)":"0",
    "Cheese":"200",
    "Fish (farmed)":"50",
    "Pig Meat":"50",
    "Poultry Meat":"50",
    "Eggs":"10",
    "Rice":"1000",
    "Groundnuts":"0",
    "Cane Sugar":"0",
    "Tofu":"0",
    "Milk":"100",
    "Oatmeal":"0",
    "Tomatoes":"50",
    "Beet Sugar":"0",
    "Other Pulses":"0",
    "Wine":"0",
    "Maize":"0",
    "Wheat & Rye":"0",
    "Berries & Grapes":"0",
    "Cassava":"0",
    "Barley":"0",
    "Other Fruit":"0",
    "Peas":"0",
    "Soy milk":"0",
    "Bananas":"50",
    "Other Vegetables":"1000",
    "Brassicas":"0",
    "Onions & Leeks":"500",
    "Potatoes":"50",
    "Nuts":"0",
    "Apples":"0",
    "Root Vegetables":"0",
    "Citrus Fruit":"0",
    "Energy":"1500"
};

let mediumD = {
    "Country":"Switzerland",
    "CarType":"Car",
    "CarFuel":"Petrol",
    "CarSize":"Medium",
    "CarKm":"30000",
    "Flight Loc":"0",
    "Flight Int":"10000",
    "Bus":"0",
    "Train":"0",
    "Cycle":"0",
    "Walk":"0",
    "Beef (beef herd)":"1000",
    "Dark Chocolate":"100",
    "Lamb & Mutton":"50",
    "Beef (dairy herd)":"0",
    "Coffee":"15",
    "Prawns (farmed)":"0",
    "Cheese":"200",
    "Fish (farmed)":"50",
    "Pig Meat":"50",
    "Poultry Meat":"50",
    "Eggs":"10",
    "Rice":"1000",
    "Groundnuts":"0",
    "Cane Sugar":"0",
    "Tofu":"0",
    "Milk":"100",
    "Oatmeal":"0",
    "Tomatoes":"50",
    "Beet Sugar":"0",
    "Other Pulses":"0",
    "Wine":"0",
    "Maize":"0",
    "Wheat & Rye":"0",
    "Berries & Grapes":"0",
    "Cassava":"0",
    "Barley":"0",
    "Other Fruit":"0",
    "Peas":"0",
    "Soy milk":"0",
    "Bananas":"0",
    "Other Vegetables":"0",
    "Brassicas":"0",
    "Onions & Leeks":"0",
    "Potatoes":"0",
    "Nuts":"0",
    "Apples":"0",
    "Root Vegetables":"0",
    "Citrus Fruit":"0",
    "Energy":"1500"
};

let smallD = {
    "Country":"Switzerland",
    "CarType":"Car",
    "CarFuel":"Hybrid",
    "CarSize":"Small",
    "CarKm":"10000",
    "Flight Loc":"0",
    "Flight Int":"0",
    "Bus":"0",
    "Train":"50000",
    "Cycle":"0",
    "Walk":"0",
    "Beef (beef herd)":"50",
    "Dark Chocolate":"100",
    "Lamb & Mutton":"50",
    "Beef (dairy herd)":"0",
    "Coffee":"15",
    "Prawns (farmed)":"0",
    "Cheese":"200",
    "Fish (farmed)":"50",
    "Pig Meat":"50",
    "Poultry Meat":"100",
    "Eggs":"10",
    "Rice":"1000",
    "Groundnuts":"0",
    "Cane Sugar":"0",
    "Tofu":"0",
    "Milk":"100",
    "Oatmeal":"0",
    "Tomatoes":"50",
    "Beet Sugar":"0",
    "Other Pulses":"0",
    "Wine":"0",
    "Maize":"0",
    "Wheat & Rye":"0",
    "Berries & Grapes":"0",
    "Cassava":"0",
    "Barley":"0",
    "Other Fruit":"0",
    "Peas":"0",
    "Soy milk":"0",
    "Bananas":"0",
    "Other Vegetables":"0",
    "Brassicas":"0",
    "Onions & Leeks":"0",
    "Potatoes":"0",
    "Nuts":"0",
    "Apples":"0",
    "Root Vegetables":"0",
    "Citrus Fruit":"0",
    "Energy":"1500"
};

